url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Add options to `rails new`" # the name of your site, e.g. ACME Corp.

twitter:
  username: stef_coetzee
  card: summary_large_image

plugins:
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-target-blank

defaults:
  - scope:
      path: ""
    values:
      image: https://i.imgur.com/ct3SYtO.png

sass:
  sourcemap: never

exclude:
  - .gitignore
  - bin
  - node_modules
  - package-lock.json
  - postcss.config.js
  - README.md
  - assets/css/tailwind.scss

# files Jekyll should not delete from .site
keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map